### ISSUE TITLE
Set up Firebase Cloud Messaging projects

### ISSUE THREAD

**Issue by jasonaowen** [PermanentOrg/notification-service#16]
We will need to set up [Firebase Cloud Messaging](https://firebase.google.com/products/cloud-messaging/) projects in our Firebase console. At the very least, we need staging and prod projects; it's not yet clear to me if we also want dev and local instances. Make sure that the appropriate people have access.

**Comment by cecilia-donnelly** [comment]
I set up a staging project.  We are deferring prod for now since @PermanentOrg/victorysquare is working exclusively on staging.  We can experiment there and go live when needed.

**Comment by jasonaowen** [comment]
> We are deferring prod for now

My main goal for this issue was to work towards the milestone, and as we discussed yesterday, we don't need to tie this issue to the mobile app going live. Closing as done!

**Comment by mithuna** [comment]
Did you add me to that project @cecilia-donnelly. I am not seeing that in my firebase console.
